defmodule ArcWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :arc

  # The session is stored in a signed cookie; its options (including the Secure flag,
  # which follows PHX_PUBLIC_SCHEME) are decided at boot in ArcWeb.Plugs.Session.
  @session_options {ArcWeb.Plugs.Session, :options, []}

  # The client's real address from a trusted proxy, before anything looks at it.
  plug ArcWeb.Plugs.ClientIp

  # Client WebSocket connections: handled before anything else in the pipeline.
  plug ArcWeb.Plugs.RealtimeUpgrade

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :arc,
    gzip: not code_reloading?,
    only: ArcWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :arc
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug ArcWeb.Plugs.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug ArcWeb.Plugs.Session
  plug ArcWeb.Router
end
